name: Deploy
on:
  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_SERVICE_PRINCIPAL_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
      AZURE_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
      AZURE_SERVICE_PRINCIPAL_TENANT: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
    steps:
      - name: check out branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: login to Azure
        run: bin/azure-cli-login

      - name: resolve latest snapshot tag
        run: source bin/resolve-latest-snapshot-tag

      - name: az output
        run: az ad signed-in-user show

      - name: aws output
        run: aws configure list-profiles

      - name: Check local dependencies
        run: bin/doctor "--tag=${LATEST_SNAPSHOT_TAG}"

      - name: Run deployment with latest
        run: bin/deploy "--tag=${LATEST_SNAPSHOT_TAG}"
