name: Deploy
on:
  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AZURE_SERVICE_PRINCIPAL_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
      AZURE_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
      AZURE_SERVICE_PRINCIPAL_TENANT: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
    steps:
      - name: check out branch
        uses: actions/checkout@v2

      - name: login to Azure
        run: bin/azure-cli-login

      - name: resolve latest snapshot tag
        run: source bin/resolve-latest-snapshot-tag

      - name: Check local dependencies
        run: bin/doctor "--tag=${LATEST_SNAPSHOT_TAG}"

      - name: Run deployment with latest
        run: bin/deploy "--tag=${LATEST_SNAPSHOT_TAG}"
